name: Add Issues to Review Board

on:
  issues:
    types:
      - opened

jobs:
  echo-input:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/youhanaNaseim/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: needs-review