name: Code Review Verifier

on: 
  push:
    branches: [ "main" ]

jobs:
  echo-input:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('./engineering/codereview_script.js')
            await script({github, context, core})
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/youhanaNaseim/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: needs-review