name: Build Fuzzer

on:
  push:
    branches: [ "main" ]
    paths:
    - 'fuzzer/**'

  pull_request:
    branches: [ "main" ]
    paths:
    - 'fuzzer/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: gcc fuzzer/HelloWorld.cpp
      