name: Proxy

on:
  push:
    branches: [ "main" ]
    paths:
    - 'proxy/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'proxy/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cargo Single Install
      run: cargo install cargo-single
    - name: Build
      run: cargo single run proxy/HelloWorld.rs

