name: Run command

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to Echo'

jobs:
  log-the-inputs:
    runs-on: youhana-mac
    steps:
      - run: |
          echo "Message: $MESSAGE"
        env:
          MESSAGE: ${{ inputs.message }}