name: Run notebook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      notebook_name:
        description: 'Notebook to run'

jobs:
  log-the-inputs:
    runs-on: youhana-mac
    steps:
      - run: |
          cd /home/youhananaseim/Source/star/
          uname -a
          pwd
          if [ -z "$NOTENOOK" ];
          then
            echo "RUN Default Notebook"
          else
            echo "Run $NOTENOOK"
          fi
        env:
          NOTENOOK: ${{ inputs.notebook_name }}