name: Run notebook

on:
  workflow_dispatch:
    inputs:
      notebook_name:
        description: 'Notebook to run'
        required: true

jobs:
  log-the-inputs:
    runs-on: youhana-mac
    steps:
      - run: |
          cd /home/youhananaseim/Source/star/
          uname -a
          pwd
          direnv reload
          echo "***************************************** $NOTEBOOK"
          nix-store --query --requisites /run/current-system |  sort | uniq
          echo "*****************************************"
        env:
          NOTENOOK: ${{ inputs.notebook_name }}