name: Run notebook

on:
  workflow_dispatch:
    inputs:
      notebook_name:
        description: 'Notebook to run'
        required: true

jobs:
  log-the-inputs:
    runs-on: youhana-nix
    steps:
      - run: |
          cd /home/youhana/src/star/
          uname -a
          pwd
          direnv reload
          nix-biuld --no-out-link tools/customer_command.nix
          customer woodchipper.local
        env:
          NOTENOOK: ${{ inputs.notebook_name }}