name: Run notebook

on:
  workflow_dispatch:
    inputs:
      picked_notebook:
        description: 'Pick Notebook to run or specify name'
        type: choice
        options:
        - webhook/headless_pbt__local.nb2
        - webhook/headless_pbt__short.nb2
      notebook_name:
        description: 'Notebook to run'

jobs:
  log-the-inputs:
    runs-on: youhana-nix
    steps:
      - run: |
          cd /home/youhana/src/star/
          uname -a
          pwd
          if [ -z "$PICKED_NOTEBOOK" ];
          then
            echo "Running Notebook : $PICKED_NOTEBOOK"
          else
            echo "Running Notebook : $NOTENOOK"
          fi
        env:
          PICKED_NOTEBOOK: ${{ inputs.picked_notebook }}
          NOTENOOK: ${{ inputs.notebook_name }}