name: Run notebook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      notebook_name:
        description: 'Notebook to run'

jobs:
  log-the-inputs:
    runs-on: youhana-mac
    steps:
      - run: |
          cd /home/youhananaseim/Source/star/
          pwd
          echo "Run $NOTENOOK"
        env:
          NOTENOOK: ${{ inputs.notebook_name }}